pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - approved-reviews-by=0
    actions:
      merge:
        method: merge
